# Generated by Django 2.1.4 on 2018-12-19 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0008_auto_20181219_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='hall name')),
                ('rows', models.IntegerField(verbose_name='rows')),
                ('cols', models.IntegerField(verbose_name='columns')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='price')),
                ('effect', models.CharField(max_length=50, verbose_name='effect')),
                ('start', models.DateTimeField(verbose_name='start time')),
                ('end', models.DateTimeField(verbose_name='end time')),
                ('hall', models.CharField(max_length=50, verbose_name='hall name')),
                ('rows', models.IntegerField(verbose_name='rows')),
                ('cols', models.IntegerField(verbose_name='columns')),
                ('seats', models.BinaryField(max_length=500, verbose_name='seats')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='movie')),
            ],
            options={
                'ordering': ('start',),
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='theater name')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('reduction', models.CharField(max_length=100, verbose_name='reduction')),
            ],
            options={
                'ordering': ('city', 'name'),
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Theater', verbose_name='theater'),
        ),
        migrations.AddField(
            model_name='hall',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Theater', verbose_name='theater'),
        ),
    ]
