# Generated by Django 2.1.4 on 2018-12-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_scene_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='theater',
        ),
    ]
