# Generated by Django 2.1.4 on 2018-12-19 16:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0005_scene_theater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='seats',
            field=jsonfield.fields.JSONField(),
        ),
    ]
