# Generated by Django 2.1.4 on 2018-12-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='actor name')),
                ('photo', models.ImageField(upload_to='images', verbose_name='photo')),
            ],
        ),
        migrations.CreateModel(
            name='ActorMovieTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='role')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Actor', verbose_name='actor')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('ename', models.CharField(max_length=100, verbose_name='english name')),
                ('cover', models.ImageField(upload_to='images', verbose_name='cover')),
                ('rating', models.IntegerField(default=0, verbose_name='rating')),
                ('popularity', models.IntegerField(default=0, verbose_name='popularity')),
                ('info', models.CharField(max_length=50, verbose_name='info')),
                ('release_date', models.DateTimeField(verbose_name='release date')),
                ('plot', models.TextField(verbose_name='plot')),
                ('on_sale', models.BooleanField(default=True)),
                ('actors', models.ManyToManyField(through='movie.ActorMovieTable', to='movie.Actor', verbose_name='actors')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='tag name')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(to='movie.Tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='actormovietable',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='movie'),
        ),
    ]
