# Generated by Django 2.1.4 on 2018-12-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-release_date', '-rating', '-popularity', 'name')},
        ),
    ]
