# Generated by Django 2.1.4 on 2018-12-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20181218_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='rating'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
