# Generated by Django 2.1.4 on 2018-12-19 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20181219_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', related_query_name='membership', to='movie.Actor', verbose_name='actor'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', related_query_name='membership', to='movie.Movie', verbose_name='movie'),
        ),
    ]
