# Generated by Django 2.1.4 on 2018-12-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20181219_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='members',
            field=models.ManyToManyField(related_name='movies', related_query_name='movie', to='movie.Membership', verbose_name='members'),
        ),
    ]
