# Generated by Django 2.1.4 on 2018-12-19 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20181219_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', related_query_name='memberships', to='movie.Actor', verbose_name='actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='members',
            field=models.ManyToManyField(related_name='movies', related_query_name='movies', to='movie.Membership', verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(related_name='movies', related_query_name='movies', to='movie.Tag', verbose_name='tags'),
        ),
    ]
