# Generated by Django 2.1.4 on 2018-12-21 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0007_auto_20181220_0036'),
        ('user', '0002_auto_20181221_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='row')),
                ('col', models.IntegerField(verbose_name='column')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Scene')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.WXUser')),
            ],
        ),
    ]
