# Generated by Django 2.1.4 on 2018-12-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181221_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='col',
            field=models.IntegerField(verbose_name='column'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.IntegerField(verbose_name='row'),
        ),
    ]
