# Generated by Django 2.1.4 on 2018-12-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('post_date',)},
        ),
    ]
